services:
  - type: web
    name: plataforma-dicox-frontend
    env: static
    region: oregon
    plan: free
    buildCommand: echo "No build required"
    staticPublishPath: ./
    envVars:
      - key: PYTHON_API_URL
        sync: false

  - type: web
    name: plataforma-dicox-backend
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 4 -b 0.0.0.0:$PORT servidor_dicox:app"
    envVars:
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false  # Render lo sincronizará automáticamente con tu BD

